version: "3.8"

services:
  app:
    build: .
    env_file:
      - .docker.env
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"

  db:
    image: postgres:15
    restart: always
    env_file:
      - .docker.env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgdata:
