/**
 * @fileoverview Test fixtures for trace data
 * @description Provides sample trace data for testing
 */

import type { YearInfo } from 'tatorscout/years';
import YearInfo2025 from 'tatorscout/years/2025.js';
import YearInfo2024 from 'tatorscout/years/2024.js';
import { Random } from 'ts-utils';
import { Trace } from 'tatorscout/trace';

export const generateTrace = (yearInfo: YearInfo) => {
	const actions = Object.keys(yearInfo.actions);

	const trace = Array.from({ length: 600 }, (_, i) => {
		let a: string | 0 = 0;
		if (Math.random() < 0.05) {
			a = Random.choose(actions);
		}

		return [i, Math.random(), Math.random(), a];
	});

	return Trace.parse(trace).unwrap().serialize();
};

/**
 * Valid trace JSON for 2025 season
 */
export const validTrace2025 = generateTrace(YearInfo2025);

/**
 * Valid trace JSON for 2024 season
 */
export const validTrace2024 = generateTrace(YearInfo2024);

/**
 * Invalid trace JSON (malformed)
 */
export const invalidTraceJSON = 'invalid json {';

/**
 * Invalid trace structure - not generated by Trace.serialize()
 */
export const invalidTraceStructure = JSON.stringify({
	points: []
});

/**
 * Valid checks array
 */
export const validChecks = JSON.stringify(['defense', 'fast', 'accurate']);

/**
 * Valid sliders object
 */
export const validSliders = JSON.stringify({
	speed: {
		value: 8,
		text: 'Very Fast',
		color: '#00ff00'
	},
	defense: {
		value: 6,
		text: 'Good Defense',
		color: '#0000ff'
	}
});

/**
 * Empty checks array
 */
export const emptyChecks = JSON.stringify([]);

/**
 * Empty sliders object
 */
export const emptySliders = JSON.stringify({});
