# docs.yml GitHub Actions example to deploy Docsify site to gh-pages
name: Deploy Docsify site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install docsify-cli -g
      - name: Build and deploy
        run: |
          docsify init ./docs
          docsify serve ./docs & # run locally for testing
          docsify build ./docs --dest ./build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
