name: Unit Tests

on:
  workflow_call:
    # secrets:
    #   GH_TOKEN:
    #     description: 'GitHub Token'
    #     required: true
  push:
    branches:
      - '*'
      - '!deploy'
      - '!gh-pages'

permissions:
  contents: read

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: username
          POSTGRES_PASSWORD: password
          POSTGRES_DB: db
        options: >-
          --health-cmd "pg_isready -U username"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: dashboard
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.16.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: v22.12.0

      - name: Install dashboard dependencies
        run: |
          cd dashboard
          echo "Installing dashboard dependencies..."
          pnpm install --frozen-lockfile

      - name: Clone the tba-webhooks repository
        run: git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/TeamTators/tba-webhooks.git tba-webhooks

      - name: Install tba-webhooks dependencies
        run: |
          cd tba-webhooks
          echo "Installing tba-webhooks dependencies..."
          pnpm install --frozen-lockfile

      - name: Create .env file for tba-webhooks
        run: |
          cd tba-webhooks
          touch .env
          echo "PORT=5555" >> .env
          echo "TBA_SECRET=webhook_secret" >> .env
          echo "REDIS_NAME=tba_webhook" >> .env

      - name: Create .env file for dashboard
        run: |
          cd dashboard
          touch .env
          echo "PORT=3000" >> .env
          echo "TBA_KEY=${{ secrets.TBA_KEY }}" >> .env
          echo "OAUTH2_CLIENT_ID=1234567890" >> .env
          echo "OAUTH2_CLIENT_SECRET=1234567890" >> .env
          export $(cat .env | xargs)

      - name: Run migrations
        run: |
          cd dashboard
          pnpm run db:migrate
          pnpm run db:push --strict --verbose --force

      - name: Run Vitest tests
        run: |
          cd dashboard
          pnpm run test:unit
