name: Unit Tests

on:
  workflow_call:
    # secrets:
    #   GH_TOKEN:
    #     description: 'GitHub Token'
    #     required: true
  push:
    branches:
      - '*'
      - '!deploy'
      - '!gh-pages'

permissions:
  contents: read

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: dashboard
          token: ${{ secrets.GH_TOKEN }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: v22.12.0

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          pnpm install --frozen-lockfile

      - name: Clone the tba-webhooks repository
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/TeamTators/tba-webhooks.git tba-webhooks

      - name: Install tba-webhooks dependencies
        run: |
          cd tba-webhooks
          echo "Installing tba-webhooks dependencies..."
          pnpm install --frozen-lockfile
          
      - name: Create env variables for tba webhooks
        run: |
          cd tba-webhooks
          touch .env
          echo "PORT=5555" >> .env
          echo TBA_SECRET="webhook_secret" >> .env
          echo "REDIS_NAME=tba_webhook" >> .env

      - name: Load .env variables
        run: |
          touch .env
          echo "DB_HOST=localhost" >> .env
          echo "DB_PORT=5432" >> .env
          echo "DB_USER=postgres" >> .env
          echo "DB_PASS=postgres" >> .env
          echo "DB_NAME=postgres" >> .env
          echo "PUBLIC_APP_NAME=test" >> .env
          echo "REDIS_NAME=some_name" >> .env
          echo "TBA_KEY=${{ secrets.TBA_KEY }}" >> .env
          echo "PUBLIC_DO_POTATO=true" >> .env
          echo "LOCAL_TBA_WEBHOOK_PATH=./tba-webhooks" >> .env
          echo "LOCAL_TBA_WEBHOOK_PORT=5555"
          echo "LOCAL_TBA_WEBHOOK_SECRET=webhook_secret" >> .env
          echo "LOCAL_TBA_WEBHOOK_REDIS_NAME=tba_webhook" >> .env
          export $(cat .env | xargs)

      - name: Run migrations
        run: |
          pnpm run db:migrate
          pnpm run db:push --strict --verbose --force

      - name: Run Vitest tests
        run: npm run test:unit
